(defproject cd-analyzer "0.1.0-SNAPSHOT"
  :description "FIXME: write"
  :dependencies [[org.clojure/clojure "1.2.0"]
                 [org.clojure/clojure-contrib "1.2.0"]
		 [mysql/mysql-connector-java "5.1.12"]
		 [org.slf4j/slf4j-api "1.6.1"]
		 [ch.qos.logback/logback-classic "0.9.24"]
		 [clj-stacktrace "0.1.3"]]
  :dev-dependencies [[leiningen/lein-swank "1.2.0-SNAPSHOT"]
		     [lein-run "1.0.0-SNAPSHOT"]
		     [com.stuartsierra/lazytest "1.0.2"]
		     [leiningen "1.3.1-SNAPSHOT"]
		     [swank-clojure "1.2.0"]
		     [clj-ssh "0.2.0-SNAPSHOT"]
		     [pallet "0.2.0-SNAPSHOT"]
		     [enlive "1.0.0-SNAPSHOT"]
		     [circumspec "0.0.12"]
		     [midje "0.1.1"]
		     [ring "0.2.5"]
		     [incanter "1.2.3-SNAPSHOT"]
		     [trammel "0.1.0"]]
  :main main)